[server]
port = 8501
fileWatcherType = "none"
enableCORS = true
enableXsrfProtection = false

[browser]
serverAddress = "0.0.0.0"

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
