[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
allowedOrigins = ["*"]

[browser]
serverAddress = "localhost"

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
